include:
  - board: nice_nano
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_BT_CENTRAL=n
  - board: nice_nano
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_BT_CENTRAL=n
  - board: nice_nano
    shield: corne_dongle
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: settings_reset
