include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
  - board: nice_nano_v2
    shield: corne_dongle
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: settings_reset
