include:
  # LEFT PERIPHERAL
  - board: nice_nano
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_BT_CENTRAL=n

  # RIGHT PERIPHERAL  
  - board: nice_nano
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_BT_CENTRAL=n
    
    #NUMPAD PERIPHERAL 
#  - board: nice_nano_v2
#    shield: corne_numpad
#    cmake-args: -DCONFIG_ZMK_SPLIT=y

  # CENTRAL (DONGLE) with ZMK Studio and OLED
  - board: nice_nano
    shield: corne_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y

  # Settings reset (for initial pairing)
  - board: nice_nano
    shield: settings_reset
