# RGB Underglow support
CONFIG_ZMK_RGB_UNDERGLOW=y
  
# Encoder support
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Mouse scroll support
CONFIG_ZMK_MOUSE=y

# Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_PM_DEVICE=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_EXT_POWER=y
